<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="arm_base_length" value="0.1" />
    <xacro:property name="arm_base_width" value="0.1" />
    <xacro:property name="arm_base_height" value="0.02" />

    <xacro:property name="arm_segment_length" value="0.3" />
    <xacro:property name="arm_segment_radius" value="0.02" />

    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
            </geometry>
            <material name="orange" />
            <origin xyz="0 0 0" rpy="0 0 0" />
        </visual>
        <collision>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
            </geometry>
        </collision>
        <xacro:box_inertia
            m="0.5" x="${arm_base_length}" y="${arm_base_width}" z="${arm_base_height}"
            o_xyz="0 0 0" o_rpy="0 0 0"
        />
    </link>
    <!-- <link name="forearm_link"></link>
    <link name="hand_link"></link> -->

    <joint name="base_arm_base_joint" type="fixed">
        <parent link="base_link" />
        <child link="arm_base_link" />
        <origin xyz="0 0 ${base_height + arm_base_height/2}" rpy="0 0 0" />
    </joint>
</robot>