<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="arm_base_length" value="0.1" />
    <xacro:property name="arm_base_width" value="0.1" />
    <xacro:property name="arm_base_height" value="0.02" />
    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="0.1 0.1 0.02" />
            </geometry>
            <material name="orange" />
            <origin xyz="0 0 0" rpy="0 0 0" />
        </visual>
    </link>
    <!-- <link name="forearm_link"></link>
    <link name="hand_link"></link> -->

    <joint name="base_arm_base_joint" type="fixed">
        <parent link="base_link" />
        <child link="arm_base_link" />
        <origin xyz="0 0 ${base_height + arm_base_height/2}" rpy="0 0 0" />
    </joint>
</robot>